// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOedGgaqd0Yss1rCSl_SfMGJEP-dTCuPo',
    appId: '1:607015743348:web:39bb718ee3ad6a7ea40621',
    messagingSenderId: '607015743348',
    projectId: 'koolb-60fff',
    authDomain: 'koolb-60fff.firebaseapp.com',
    storageBucket: 'koolb-60fff.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAspvABo_85tOKcGF1JRhSQEGwCnGWjLiw',
    appId: '1:607015743348:android:fddb51db022eb234a40621',
    messagingSenderId: '607015743348',
    projectId: 'koolb-60fff',
    storageBucket: 'koolb-60fff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgCpA7jTIvhpt6f6uEd31K0jNLC9jpNbI',
    appId: '1:607015743348:ios:04725ec588aec19fa40621',
    messagingSenderId: '607015743348',
    projectId: 'koolb-60fff',
    storageBucket: 'koolb-60fff.appspot.com',
    iosClientId: '607015743348-vbn8e4juailcmpq6o8cf2rcgpo6g3n3k.apps.googleusercontent.com',
    iosBundleId: 'com.example.koolb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgCpA7jTIvhpt6f6uEd31K0jNLC9jpNbI',
    appId: '1:607015743348:ios:04725ec588aec19fa40621',
    messagingSenderId: '607015743348',
    projectId: 'koolb-60fff',
    storageBucket: 'koolb-60fff.appspot.com',
    iosClientId: '607015743348-vbn8e4juailcmpq6o8cf2rcgpo6g3n3k.apps.googleusercontent.com',
    iosBundleId: 'com.example.koolb',
  );
}
